SELECT
  daily_trends.*,

  securities_with_performance.id as id,
  securities_with_performance.address as address,
  securities_with_performance.beta as beta,
  securities_with_performance.ceo as ceo,
  securities_with_performance.change_percent as change_percent,
  securities_with_performance.change_price as change_price,
  securities_with_performance.cik as cik,
  securities_with_performance.city as city,
  securities_with_performance.country as country,
  securities_with_performance.currency as currency,
  securities_with_performance.cusip as cusip,
  securities_with_performance.day_1_performance as day_1_performance,
  securities_with_performance.day_5_performance as day_5_performance,
  securities_with_performance.day_200_sma as securities_with_performance_day_200_sma,
  securities_with_performance.day_50_sma as securities_with_performance_day_50_sma,
  securities_with_performance.day_high as securities_with_performance_day_high,
  securities_with_performance.day_low as securities_with_performance_day_low,
  securities_with_performance.dcf_difference as dcf_difference,
  securities_with_performance.dcf as dcf,
  securities_with_performance.description as description,
  securities_with_performance.eps as eps,
  securities_with_performance.exchange as exchange,
  securities_with_performance.exchange_short_name as exchange_short_name,
  securities_with_performance.full_time_employees as full_time_employees,
  securities_with_performance.id as securities_with_performance_id,
  securities_with_performance.image as image,
  securities_with_performance.industry as industry,
  securities_with_performance.inserted_at as securities_with_performance_inserted_at,
  securities_with_performance.ipo_date as ipo_date,
  securities_with_performance.is_adr as is_adr,
  securities_with_performance.is_etf as is_etf,
  securities_with_performance.is_fund as is_fund,
  securities_with_performance.isin as isin,
  securities_with_performance.last_dividend as last_dividend,
  securities_with_performance.market_cap as market_cap,
  securities_with_performance.max_performance as max_performance,
  securities_with_performance.month_1_performance as month_1_performance,
  securities_with_performance.month_3_performance as month_3_performance,
  securities_with_performance.month_6_performance as month_6_performance,
  securities_with_performance.name as name,
  securities_with_performance.open as securities_with_performance_open,
  securities_with_performance.pe as pe,
  securities_with_performance.previous_close as securities_with_performance_previous_close,
  securities_with_performance.price as price,
  securities_with_performance.sector as sector,
  securities_with_performance.shares_outstanding as shares_outstanding,
  securities_with_performance.state as state,
  securities_with_performance.symbol as securities_with_performance_symbol,
  securities_with_performance.updated_at as securities_with_performance_updated_at,
  securities_with_performance.volume as volume,
  securities_with_performance.volume_avg as volume_avg,
  securities_with_performance.website as website,
  securities_with_performance.year_1_performance as year_1_performance,
  securities_with_performance.year_3_performance as year_3_performance,
  securities_with_performance.year_5_performance as year_5_performance,
  securities_with_performance.year_10_performance as year_10_performance,
  securities_with_performance.year_high as securities_with_performance_year_high,
  securities_with_performance.year_low as securities_with_performance_year_low,
  securities_with_performance.ytd_performance as ytd_performance,
  securities_with_performance.zip as zip_code
FROM
  securities_with_performance
FULL OUTER JOIN
  (SELECT DISTINCT ON(symbol) symbol,
    daily_trends.close as daily_trends_close,
    daily_trends.close_above_day_200_sma as close_above_day_200_sma,
    daily_trends.close_above_day_50_sma as close_above_day_50_sma,
    daily_trends.date as daily_trends_date,
    daily_trends.day_200_sma as daily_trends_day_200_sma,
    daily_trends.day_50_sma as daily_trends_day_50_sma,
    daily_trends.day_50_sma_above_day_200_sma as day_50_sma_above_day_200_sma,
    daily_trends.id as daily_trends_id,
    daily_trends.inserted_at as daily_trends_inserted_at,
    daily_trends.is_valid as daily_trends_is_valid,
    daily_trends.near_day_20_high as daily_trends_near_day_20_high,
    daily_trends.near_day_50_high as daily_trends_near_day_50_high,
    daily_trends.near_day_100_high as daily_trends_near_day_100_high,
    daily_trends.previous_close as daily_trends_previous_close,
    daily_trends.previous_close_above_day_200_sma as previous_close_above_day_200_sma,
    daily_trends.previous_close_above_day_50_sma as previous_close_above_day_50_sma,
    daily_trends.previous_day_200_sma as previous_day_200_sma,
    daily_trends.previous_day_50_sma as previous_day_50_sma,
    daily_trends.previous_day_50_sma_above_day_200_sma as previous_day_50_sma_above_day_200_sma,
    daily_trends.previous_trend as previous_trend,
    daily_trends.previous_truthy_flags_count as previous_truthy_flags_count,
    daily_trends.symbol as daily_trends_symbol,
    daily_trends.trend as trend,
    daily_trends.trend_change as trend_change,
    daily_trends.truthy_flags_count as truthy_flags_count,
    daily_trends.updated_at as daily_trends_updated_at,
    daily_trends.volume as daily_trends_volume
  FROM daily_trends WHERE is_valid = true ORDER BY symbol, date DESC) daily_trends
ON
  securities_with_performance.symbol = daily_trends.symbol
WHERE
  securities_with_performance.symbol not like '%.%'
AND
  securities_with_performance.symbol not like '%-%'
OR
  securities_with_performance.symbol in ('BRK-A', 'BRK-B')
;